version: 2
updates:
  - package-ecosystem: "github-actions" 
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Checkmarx/ast-galactica-team"
  - package-ecosystem: "nuget"
    directory: "/" 
    schedule:
      interval: "daily"
    reviewers:
      - "hmmachadocx"
