// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ast_visual_studio_extension.CxExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCxWindowPackageString = "63d5f3b4-a254-4bef-974b-0733c306ed2c";
        public static Guid guidCxWindowPackage = new Guid(guidCxWindowPackageString);

        public const string guidCxWindowPackageCmdSetString = "e46cd6d8-268d-4e77-9074-071e72a25f39";
        public static Guid guidCxWindowPackageCmdSet = new Guid(guidCxWindowPackageCmdSetString);

        public const string CxImagesString = "cca5f138-eee9-4fc7-8f65-fce867b52e22";
        public static Guid CxImages = new Guid(CxImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CxWindowCommandId = 0x0100;
        public const int MyMenuGroup = 0x1020;
        public const int CxWindowCmdId = 0x0101;
        public const int TWToolbar = 0x1000;
        public const int TWToolbarGroup = 0x1050;
        public const int ScansCombo = 0x0103;
        public const int ScansComboGetList = 0x0104;
        public const int cxlogo = 0x0001;
    }
}