name: Checkmarx One Scan

on: [ pull_request, workflow_dispatch ]

jobs:
  cx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@6c56658230f79c227a55120e9b24845d574d5225 #main
        with:
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          additional_params: --tags phoenix --threshold "sca-high=1;sca-medium=1;sca-low=1"
