name: Checkmarx One visual studio extension CI

on: [pull_request, workflow_dispatch]

permissions:
  write-all

jobs:
  UI-tests:
    name: Checkmarx One visual studio extension CI / UI-tests
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      
      - name: Restore NuGet packages
        run: nuget restore
      
      - name: Build solution
        run: msbuild ast-visual-studio-extension.sln /p:Configuration=Release
      
      - name: Install Checkmarx Extension
        run: |
          $vsixPath = Get-ChildItem -Path ".\ast-visual-studio-extension\bin\Release\*.vsix" -Recurse | Select-Object -First 1
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe" /quiet "$vsixPath"
          Start-Sleep -Seconds 30
      
      - name: Verify Extension Installation
        run: |
          $extensionPath = "C:\Users\runneradmin\AppData\Local\Microsoft\VisualStudio\17.0_*\Extensions"
          if (!(Test-Path -Path "$extensionPath\*\ast-visual-studio-extension*")) {
            throw "Extension not found in expected location"
          }
      
      - name: Run UI Tests
        run: |
          $testDll = ".\UITests\bin\Release\UITests.dll"
          if (!(Test-Path $testDll)) {
            Write-Error "Test DLL not found at: $testDll"
            exit 1
          }
          
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" `
            /InIsolation `
            /Logger:"trx;LogFileName=uitest-results.trx" `
            $testDll
        continue-on-error: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/*.trx
            ${{ github.workspace }}\Screenshots