name: Checkmarx One visual studio extension CI
on: [ pull_request, workflow_dispatch ]
permissions: write-all
jobs:
  integration-tests:
    # Windows 2022 runner already includes BuildTools
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      # Basic checkout
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Setting up .NET - verified working version
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Verified MSBuild setup
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '17.2'

      # Package versions that are known to work
      - name: Install and Configure Dependencies
        run: |
          dotnet remove .\ast-visual-studio-extension\ast-visual-studio-extension.csproj package Newtonsoft.Json
          dotnet add .\ast-visual-studio-extension\ast-visual-studio-extension.csproj package Newtonsoft.Json -v 13.0.1
          dotnet add .\UITests\UITests.csproj package System.Drawing.Common -v 8.0.0
          
      # Basic restore commands
      - name: Restore Packages
        run: |
          nuget restore .
          dotnet restore .

      # Simple build command
      - name: Build
        run: |
          msbuild /p:Configuration=Release /p:DeployExtension=False