name: Checkmarx One visual studio extension CI

on: [ pull_request, workflow_dispatch ]

permissions: write-all

jobs:
  integration-tests:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2022buildtools -y

      - name: Add MSBuild to PATH
        shell: pwsh
        run: |
          $vsPath = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
          $msbuildPath = Join-Path $vsPath "MSBuild\Current\Bin"
          if (-Not (Test-Path $msbuildPath)) {
            throw "MSBuild path not found: $msbuildPath"
          }
          echo "$msbuildPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify MSBuild
        shell: pwsh
        run: |
          if (-Not (Get-Command "msbuild" -ErrorAction SilentlyContinue)) {
            throw "MSBuild not found in PATH"
          } else {
            Write-Host "MSBuild is available"
          }

      - name: Restore NuGet packages
        run: nuget restore .

      - name: Restore
        run: dotnet restore .

      - name: Build
        run: msbuild /p:Configuration=Release /p:DeployExtension=False
