name: Checkmarx One visual studio extension CI
on: [ pull_request, workflow_dispatch ]
permissions: write-all
jobs:
  integration-tests:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Setting up tools
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '17.2'

      # Install required packages
      - name: Add Required Packages
        run: |
          dotnet add .\UITests\UITests.csproj package System.Drawing.Common
          dotnet add .\ast-visual-studio-extension\ast-visual-studio-extension.csproj package System.Resources.Extensions

      # Basic restore
      - name: Restore
        run: |
          nuget restore
          dotnet restore

      # Build with specific resource handling for VSIX
      - name: Build
        run: |
          msbuild /p:Configuration=Release /p:DeployExtension=False /p:GenerateResourceUsePreserializedResources=true /p:VSSDKTargetPlatformRegRootSuffix=Exp

      # Generate and upload coverage report
      - name: Generate code coverage report
        run: dotnet test --collect:"XPlat Code Coverage"
        
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: '**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: Coverage Report
          recreate: true
          path: code-coverage-results.md