name: Checkmarx One Visual Studio Extension CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  integration-tests:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@3a16d909a1f3bbc65b52f8270d475d905e7d3e44 #v1

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@1.3.1
        with:
          vs-version: '17.2'

      - name: Restore NuGet packages
        run: nuget restore

      - name: Restore .NET Packages
        run: dotnet restore

      - name: Build Solution
        run: msbuild /p:Configuration=Release /p:DeployExtension=False

      - name: Run Tests
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        run: vstest.console.exe /InIsolation ./ast-visual-studio-extension-tests/bin/Release/net6.0-windows/ast-visual-studio-extension-tests.dll
