name: Checkmarx One visual studio extension CI

on: [ pull_request, workflow_dispatch ]

permissions: write-all

jobs:
  integration-tests:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '17.2'

      - name: Restore NuGet packages
        run: msbuild -t:restore  
      
      - name: Build
        run: msbuild /p:Configuration=Release /p:DeployExtension=False
        
      - name: Tests
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        run: vstest.console.exe /InIsolation .\ast-visual-studio-extension-tests\bin\Release\net472\ast-visual-studio-extension-tests.dll
        
       
