name: AST visual studio extension CI

on: [ pull_request, workflow_dispatch ]


jobs:
  integration-tests:
    runs-on: windows-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore
        run: dotnet restore

      - name: Build
        run: msbuild /p:Configuration=Release /p:DeployExtension=False
        
      - name: Tests
        run: vstest.console.exe **\*.Tests.dll