name: Checkmarx One visual studio extension CI
on: [ pull_request, workflow_dispatch ]
permissions: write-all
jobs:
  integration-tests:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Install Visual Studio components with VSSDK
      - name: Install Visual Studio components
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '17.2'
          vs-prerelease: false
          include-prerelease: false

      # Install VSSDK
      - name: Install VSSDK
        run: |
          nuget install Microsoft.VSSDK.BuildTools -Version 17.0.5232
          
      # Restore packages
      - name: Restore NuGet packages
        run: |
          nuget restore .
          dotnet restore .

      # Build with resource generation property
      - name: Build
        run: |
          msbuild /p:Configuration=Release /p:DeployExtension=False /p:GenerateResourceUsePreserializedResources=true

      # Run tests with coverage
      - name: Run Tests with Code Coverage
        shell: pwsh
        env:
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        continue-on-error: true
        run: |
          $testDll = ".\ast-visual-studio-extension-tests\bin\Release\net60-windows\ast-visual-studio-extension-tests.dll"
          if (Test-Path $testDll) {
            vstest.console.exe /EnableCodeCoverage $testDll
          } else {
            Write-Warning "Test DLL not found: $testDll - Continuing without tests"
          }