name: Checkmarx One visual studio extension CI

on: [pull_request, workflow_dispatch]

permissions:
  write-all

jobs:
  UI-tests:
    name: Checkmarx One visual studio extension CI / UI-tests
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
      
      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      
      - name: Restore NuGet packages
        run: nuget restore
      
      - name: Build solution
        run: msbuild ast-visual-studio-extension.sln /p:Configuration=Release
      
      - name: Install Checkmarx Extension
        shell: pwsh
        run: |
          $vsixPath = Get-ChildItem -Path ".\ast-visual-studio-extension\bin\Release\*.vsix" -Recurse | Select-Object -First 1
          Write-Host "Installing VSIX from: $($vsixPath.FullName)"
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe" /quiet "$($vsixPath.FullName)"
          Start-Sleep -Seconds 30
      
      - name: Run UI Tests
        shell: pwsh
        run: |
          $testDll = ".\UITests\bin\Release\UITests.dll"
          Write-Host "Running tests from: $testDll"
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" `
            /InIsolation `
            /Logger:"trx;LogFileName=uitest-results.trx" `
            "$testDll"
        continue-on-error: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/*.trx
            ${{ github.workspace }}\Screenshots