name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  check-dependabot-commits:
    name: Check if dependabot commits exist
    outputs:
      isDependabot: ${{ steps.check-dependabot.outputs.dependabotExists }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if dependabot commits exist
        id: check-dependabot
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "dependabotExists=$(echo $GITHUB_CONTEXT | jq '.event.commits[0].author | any(. == "dependabot[bot]")')" >> $GITHUB_OUTPUT

  delete-tag:
    runs-on: ubuntu-latest
    needs: check-dependabot-commits
    if: ${{needs.check-dependabot-commits.outputs.isDependabot == 'false'}}
    steps:
      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@82600feb9527126eca69833f07bafe53279bd9b4 #v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: 2.0.0-nightly

  nightly:
    needs: delete-tag
    if: ${{needs.check-dependabot-commits.outputs.isDependabot == 'false'}}
    uses: Checkmarx/ast-visual-studio-extension/.github/workflows/release.yml@main
    with:
      tag: "2.0.0-nightly"
      dev: true
      cliTag: "2.0.0-nightly"
    secrets: inherit
