name: PR Labeler
on:
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      pull-requests: write  # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: step-security/pr-labeler-action@ef1aaf0814c671e210aced271e5973b598049990 # v5.0.5
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
