name: Release

on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Increment VSIX version
        id: vsix_version
        uses: timheuer/vsix-version-stamp@v1
        with:
          manifest-file: ast-visual-studio-extension\source.extension.vsixmanifest
          
      - run: dotnet restore
      
      - run: msbuild /p:Configuration=Release /p:DeployExtension=False

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          files: '.\ast-visual-studio-extension\bin\Release\ast-visual-studio-extension.vsix'
      
      - name: Publish Release
        uses: cezarypiatek/VsixPublisherAction@0.2
        with:
          extension-file: '.\ast-visual-studio-extension\bin\Release\ast-visual-studio-extension.vsix'
          publish-manifest-file: '.\vs-publish.json'
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
