name: Release

on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17.2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Increment VSIX version
        id: vsix_version
        uses: timheuer/vsix-version-stamp@v2
        with:
          manifest-file: ast-visual-studio-extension\source.extension.vsixmanifest
      
      - name: Restore NuGet packages
        run: msbuild .\ast-visual-studio-extension\ast-visual-studio-extension.csproj -t:restore
      
      - run: msbuild .\ast-visual-studio-extension\ast-visual-studio-extension.csproj /p:Configuration=Release /p:DeployExtension=False
