name: Test VSIX Version Stamp

on:
  workflow_dispatch:

jobs:
  test-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run VSIX Version Stamp
        id: vsix_version
        uses: ./.github/actions/vsix-version-stamp
        with:
          version-type: 'build'
          manifest-file: 'ast-visual-studio-extension/source.extension.vsixmanifest'
          build-number: ${{ github.run_number }}
          version-number: '' 

      - name: Output version number
        run: echo "Version number is ${{ steps.vsix_version.outputs.version-number }}"
