name: Test Release

on:
  push:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17.2'

      - name: Set env
        run: echo "RELEASE_VERSION=dev" >> $GITHUB_ENV

      - name: Increment VSIX version
        id: vsix_version
        uses: timheuer/vsix-version-stamp@v2
        with:
          manifest-file: ast-visual-studio-extension\source.extension.vsixmanifest

      - name: Restore NuGet packages
        run: msbuild -t:restore  

      - run: msbuild /p:Configuration=Release /p:DeployExtension=False

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ast-visual-studio-extension.vsix
          path: .\ast-visual-studio-extension\bin\Release\ast-visual-studio-extension.vsix